### ISSUE TITLE
gtd.org_archive is not in `org-mode'

### ISSUE THREAD

**Issue by Hardy5012** [CodeFalling/spacemacs-private#1]
使用你的配置时，提示
gtd.org_archive is not in `org-mode'
是不是配置中的这行的gtd.org_archive文件名要以org后缀
setq org-agenda-file-gtd-archive (expand-file-name "gtd.org_archive" org-agenda-dir)

**Comment by Hardy5012** [comment]
理解有误

**Comment by xcodebuild** [comment]
顺便这套配置其实已经不用很久了，仅供参考

**Comment by Hardy5012** [comment]
不过这块还是有问题，org-agenda-get-day-entries: Agenda file gtd.org_archive is not in `org-mode'。而且C-c a a看不到任务
