### ISSUE TITLE
我按你的步骤安装提示有三个错误

### ISSUE THREAD

**Issue by ptcgh** [CodeFalling/spacemacs-private#2]
由于网络问题安装了好几遍，最后一次总算全部下载下来，提示以下错误：
Found 22 new package(s) to install...
--> refreshing package archive: gnu-cn... [3/3]
--> installing package: org-octopress@zilongshanren-org... [1/22]
An error occurred while installing org-octopress (error: (file-error https://elpa.zilongshanren.com/gnu/org-20161102.tar Bad gateway))
--> installing package: org-plus-contrib@spacemacs-org... [2/22]
An error occurred while installing org-plus-contrib (error: (file-error https://elpa.zilongshanren.com/org/org-plus-contrib-20161102.tar Gateway time-out))
--> installing package: tide@typescript... [5/22]
An error occurred while installing tide (error: (file-error https://elpa.zilongshanren.com/melpa/tide-20161103.1005.tar Bad gateway))
--> installing package: youdao-dictionary@chinese... [22/22]
我直接复制那几个文件在浏览器下载也可以下载，但是很慢。

**Comment by xcodebuild** [comment]
`M-x package-refresh-contents`

顺便，我的配置只是把 @zilongshanren 的配置 fork 过来关掉一些自己不用的而已。建议你直接使用他的配置。

**Comment by ptcgh** [comment]
好的，谢谢
